-- Insertion des pièces automobiles - Catalogue complet

-- Freinage (12 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('FRN-BSH-001', 'Plaquette frein avant Bosch QuietCast', 'Plaquette frein avant haute performance, epaisseur 17mm, coefficient friction mu=0.42. Compatible Renault Clio 3/4, Dacia Logan, Peugeot 206. Certification ECE R90, faible bruit. Remplacement recommande tous les 30 000 km.', 'Freinage', 'Bosch', 58.90, 22, 5),
('FRN-FRD-002', 'Plaquette frein arriere Ferodo Eco-Friction', 'Plaquette frein arriere a faible poussiere, epaisseur 15mm. Compatible Peugeot 208, Citroen C3, Renault Symbol. Formule eco-friction, disques preserves. Remplacement recommande tous les 35 000 km.', 'Freinage', 'Ferodo', 52.00, 18, 5),
('FRN-BRM-003', 'Disque frein avant Brembo ventile 266mm', 'Disque frein avant ventile 266mm, epaisseur 22mm, acier haute teneur carbone. Compatible Volkswagen Golf 5/6, Polo, Passat. Dissipation thermique elevee, vibrations reduites. Remplacement recommande tous les 60 000 km.', 'Freinage', 'Brembo', 110.00, 14, 5),
('FRN-TXT-004', 'Disque frein arriere Textar plein 249mm', 'Disque frein arriere plein 249mm, epaisseur 10mm. Compatible Peugeot 301, Renault Logan, Dacia Sandero. Usinage precis, freinage stable. Remplacement recommande tous les 70 000 km.', 'Freinage', 'Textar', 88.00, 12, 5),
('FRN-TRW-005', 'Etrier frein avant TRW piston 54mm', 'Etrier frein avant piston 54mm avec support. Compatible Renault Megane 3, Peugeot 308, Dacia Duster. Etancheite renforcee, course stable. Controle recommande a 80 000 km.', 'Freinage', 'TRW', 175.00, 6, 3),
('FRN-ATE-006', 'Etrier frein arriere ATE piston 38mm', 'Etrier frein arriere piston 38mm pour frein de stationnement. Compatible Volkswagen Golf 7, Tiguan, Passat. Protection anticorrosion, freinage progressif. Controle recommande a 80 000 km.', 'Freinage', 'ATE', 160.00, 6, 3),
('FRN-ATE-007', 'Maitre-cylindre frein ATE 23.8mm', 'Maitre-cylindre frein 23.8mm, double circuit. Compatible Renault Clio 4, Peugeot 208, Dacia Logan. Course de pedalier stable, etancheite durable. Remplacement recommande a 120 000 km.', 'Freinage', 'ATE', 210.00, 5, 3),
('FRN-BSH-008', 'Flexible frein avant Bosch 420mm', 'Flexible frein avant 420mm, gaine renforcee. Compatible Peugeot 206, Citroen C3, Fiat Punto. Tresse anti-fissure, reponse rapide. Remplacement recommande tous les 80 000 km.', 'Freinage', 'Bosch', 28.00, 28, 5),
('FRN-FRD-009', 'Cylindre de roue arriere Ferodo 19mm', 'Cylindre de roue arriere 19mm, corps alu. Compatible Renault Logan, Dacia Sandero, Chevrolet Aveo. Freinage regulier, fuite limitee. Remplacement recommande tous les 60 000 km.', 'Freinage', 'Ferodo', 48.00, 16, 5),
('FRN-TXT-010', 'Tambour de frein arriere Textar 203mm', 'Tambour de frein arriere 203mm, surface trempee. Compatible Renault Clio 3, Peugeot 206, Chevrolet Aveo. Usure lente, freinage stable. Remplacement recommande tous les 90 000 km.', 'Freinage', 'Textar', 98.00, 10, 5),
('FRN-TRW-011', 'Plaquette frein mixte TRW semi-metallique', 'Plaquette semi-metallique, bonne resistance thermique. Compatible Hyundai i30, Kia Ceed, Toyota Corolla. Performance constante, usure moderee. Remplacement recommande tous les 40 000 km.', 'Freinage', 'TRW', 62.00, 20, 5),
('FRN-BRM-012', 'Flexible frein arriere Brembo 360mm', 'Flexible frein arriere 360mm, raccords zinc. Compatible Renault Megane 3, Dacia Duster, Peugeot 308. Bonne resistance chaleur, maintenance simple. Remplacement recommande tous les 80 000 km.', 'Freinage', 'Brembo', 32.00, 24, 5);

-- Filtration (12 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('FLT-MNF-001', 'Filtre a huile Mann-Filter W 712/95', 'Filtre a huile haut debit, clapet anti-retour silicone. Compatible Renault Clio 3 1.5 dCi, Dacia Logan 1.5 dCi, Renault Megane 2. Filtration 20 microns, moteur protege. Remplacement recommande tous les 10 000 km.', 'Filtration', 'Mann-Filter', 18.90, 50, 10),
('FLT-MHL-002', 'Filtre a air Mahle LX 2046', 'Filtre a air papier multi-plis, surface 0.42 m2. Compatible Peugeot 208, Citroen C3, Renault Clio 4. Debit air stable, consommation reduite. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Mahle', 24.50, 42, 10),
('FLT-FRM-003', 'Filtre carburant Fram G 10156', 'Filtre carburant diesel 5 microns avec separateur eau. Compatible Peugeot 301 1.6 HDi, Citroen C4 1.6 HDi, Ford Fiesta 1.4 TDCi. Protection injection, demarrage facile. Remplacement recommande tous les 20 000 km.', 'Filtration', 'Fram', 32.00, 28, 10),
('FLT-KAN-004', 'Filtre a air sport K&N panel', 'Filtre a air sport lavable, debit +30%. Compatible Volkswagen Golf 6 1.4 TSI, Polo 1.2 TSI, Passat 1.8 TSI. Media coton huile, reutilisable. Nettoyage recommande tous les 50 000 km.', 'Filtration', 'K&N', 95.00, 12, 5),
('FLT-VAL-005', 'Filtre habitacle Valeo charbon actif', 'Filtre habitacle charbon actif, retient odeurs et pollen. Compatible Renault Megane 3, Dacia Duster, Peugeot 308. Confort interieur, vitres sans buée. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Valeo', 28.00, 45, 10),
('FLT-SFM-006', 'Filtre gasoil Sofima S 1790', 'Filtre gasoil haute efficacite, corps metallique. Compatible Fiat Punto 1.3 Multijet, Peugeot 206 1.4 HDi, Renault Symbol 1.5 dCi. Protege pompe haute pression. Remplacement recommande tous les 20 000 km.', 'Filtration', 'Sofima', 29.50, 30, 10),
('FLT-MNF-007', 'Filtre a huile Mann-Filter HU 816x', 'Filtre a huile cartouche, soupape bypass integree. Compatible Volkswagen Golf 7 1.6 TDI, Passat 2.0 TDI, Tiguan 2.0 TDI. Filtration fine 25 microns. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Mann-Filter', 21.00, 36, 10),
('FLT-MHL-008', 'Filtre habitacle Mahle LAK 80', 'Filtre habitacle anti-pollen, media electret. Compatible Hyundai i30, Kia Ceed, Hyundai Tucson. Air propre, ventilation efficace. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Mahle', 30.00, 32, 10),
('FLT-FRM-009', 'Filtre a air Fram CA 10254', 'Filtre a air haute capacite, joints mousse. Compatible Toyota Corolla, Yaris, RAV4. Bon debit air, filtre poussiere fine. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Fram', 23.50, 40, 10),
('FLT-KAN-010', 'Filtre a huile K&N Performance HP-1004', 'Filtre a huile performance, ecrou 17mm pour demontage rapide. Compatible Toyota Corolla, Hyundai i20, Kia Rio. Media haute resistance, pression stable. Remplacement recommande tous les 10 000 km.', 'Filtration', 'K&N', 45.00, 20, 10),
('FLT-VAL-011', 'Filtre carburant Valeo diesel 587528', 'Filtre carburant diesel 4 microns, joint etanche. Compatible Peugeot 301 1.6 HDi, Citroen C4 1.6 HDi, Ford Focus 1.6 TDCi. Injection protegee, demarrage stable. Remplacement recommande tous les 20 000 km.', 'Filtration', 'Valeo', 35.00, 24, 10),
('FLT-SFM-012', 'Filtre habitacle Sofima pollen S 3150', 'Filtre habitacle pollen, cadre rigide. Compatible Renault Clio 3, Dacia Logan, Renault Symbol. Debit air constant, odeurs reduites. Remplacement recommande tous les 15 000 km.', 'Filtration', 'Sofima', 22.00, 50, 10);

-- Suspension & Direction (12 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('SUS-MNR-001', 'Amortisseur avant Monroe Reflex', 'Amortisseur avant gaz bitube, tige 20mm, course 150mm. Compatible Peugeot 308, Renault Megane 3, Citroen C4. Tenue de route stable, confort optimise. Remplacement recommande tous les 80 000 km.', 'Suspension & Direction', 'Monroe', 175.00, 8, 3),
('SUS-KYB-002', 'Amortisseur arriere KYB Excel-G', 'Amortisseur arriere gaz, calibration standard. Compatible Renault Clio 4, Dacia Sandero, Peugeot 208. Rebond controle, usure reguliere. Remplacement recommande tous les 80 000 km.', 'Suspension & Direction', 'KYB', 150.00, 10, 3),
('SUS-SCH-003', 'Coupelle amortisseur Sachs avec butee', 'Coupelle amortisseur avec roulement, diametre 82mm. Compatible Volkswagen Golf 6, Polo, Passat. Direction souple, bruit reduit. Remplacement recommande tous les 80 000 km.', 'Suspension & Direction', 'Sachs', 85.00, 14, 5),
('SUS-MOG-004', 'Rotule de suspension Moog', 'Rotule de suspension conique 18mm, graisse longue duree. Compatible Ford Focus, Mondeo, EcoSport. Tenue precise, jeu limite. Remplacement recommande tous les 60 000 km.', 'Suspension & Direction', 'Moog', 45.00, 20, 5),
('SUS-SKF-005', 'Roulement de roue avant SKF', 'Roulement de roue avant, ABS integre 75mm. Compatible Toyota Corolla, Hyundai i30, Kia Ceed. Etancheite renforcee, roulage silencieux. Remplacement recommande tous les 90 000 km.', 'Suspension & Direction', 'SKF', 120.00, 12, 5),
('SUS-FAG-006', 'Roulement de roue arriere FAG', 'Roulement de roue arriere, cartouche 72mm. Compatible Peugeot 206, 207, Citroen C3. Faible friction, longue duree. Remplacement recommande tous les 90 000 km.', 'Suspension & Direction', 'FAG', 110.00, 12, 5),
('SUS-LMF-007', 'Biellette barre stabilisatrice Lemforder', 'Biellette barre stabilisatrice 270mm, rotules etanches. Compatible Dacia Duster, Dokker, Renault Logan. Stabilite en virage, bruit reduit. Remplacement recommande tous les 50 000 km.', 'Suspension & Direction', 'Lemforder', 38.00, 25, 5),
('SUS-KYB-008', 'Silentbloc bras inferieur KYB', 'Silentbloc bras inferieur, diametre 52mm. Compatible Peugeot 301, Renault Symbol, Dacia Logan. Absorption vibrations, usure reguliere. Remplacement recommande tous les 70 000 km.', 'Suspension & Direction', 'KYB', 55.00, 18, 5),
('SUS-SCH-009', 'Rotule direction Sachs', 'Rotule direction filetage M14, conique 17mm. Compatible Volkswagen Golf 5, Polo, Passat. Direction precise, jeu reduit. Remplacement recommande tous les 60 000 km.', 'Suspension & Direction', 'Sachs', 52.00, 18, 5),
('SUS-MOG-010', 'Biellette de direction Moog', 'Biellette de direction 300mm, pas M12. Compatible Kia Rio, Hyundai i20, Toyota Yaris. Reponse stable, long cycle. Remplacement recommande tous les 60 000 km.', 'Suspension & Direction', 'Moog', 48.00, 20, 5),
('SUS-SKF-011', 'Palier de suspension SKF', 'Palier de suspension superieur, axe 14mm. Compatible Ford Fiesta, Peugeot 208, Renault Clio 4. Direction souple, bruit limite. Remplacement recommande tous les 80 000 km.', 'Suspension & Direction', 'SKF', 95.00, 12, 5),
('SUS-LMF-012', 'Triangle suspension Lemforder', 'Triangle suspension complet avec rotule, acier embouti renforce. Compatible Peugeot 308, Citroen C4, Renault Megane 3. Rigidite optimisee, usure lente. Remplacement recommande tous les 90 000 km.', 'Suspension & Direction', 'Lemforder', 160.00, 8, 3);

-- Distribution & Moteur (10 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('DST-GAT-001', 'Courroie de distribution Gates 111 dents', 'Courroie de distribution 111 dents, largeur 25mm. Compatible Renault Clio 3 1.5 dCi, Dacia Logan 1.5 dCi, Renault Symbol 1.5 dCi. Caoutchouc HNBR, tenue thermique. Remplacement recommande tous les 90 000 km.', 'Distribution & Moteur', 'Gates', 95.00, 10, 2),
('DST-CNT-002', 'Kit distribution Continental 1.2', 'Kit distribution avec courroie et galets, largeur 23mm. Compatible Peugeot 208 1.2, Citroen C3 1.2, Peugeot 301 1.2. Calage stable, usure reguliere. Remplacement recommande tous les 90 000 km.', 'Distribution & Moteur', 'Continental', 320.00, 6, 2),
('DST-DYC-003', 'Kit distribution Dayco 1.6', 'Kit distribution avec tendeur automatique. Compatible Renault Megane 3 1.6, Dacia Duster 1.6, Renault Logan 1.6. Tension constante, bruit reduit. Remplacement recommande tous les 90 000 km.', 'Distribution & Moteur', 'Dayco', 280.00, 6, 2),
('DST-INA-004', 'Galet tendeur INA 60mm', 'Galet tendeur metallique 60mm, roulement scelle. Compatible Volkswagen Golf 6 1.6 TDI, Passat 2.0 TDI, Tiguan 2.0 TDI. Rotation stable, faible friction. Remplacement recommande tous les 90 000 km.', 'Distribution & Moteur', 'INA', 75.00, 18, 5),
('DST-SNR-005', 'Pompe a eau SNR turbine metal', 'Pompe a eau turbine metal, debit 110 L/min. Compatible Peugeot 301 1.6, Citroen C4 1.6, Renault Symbol 1.6. Etancheite renforcee, temperature stable. Remplacement recommande avec la courroie.', 'Distribution & Moteur', 'SNR', 120.00, 12, 5),
('DST-GAT-006', 'Courroie accessoires Gates 6PK1710', 'Courroie accessoires 6PK 1710, micro nervures. Compatible Toyota Corolla 1.6, Hyundai i30 1.6, Kia Ceed 1.6. Flexibilite durable, bruit limite. Remplacement recommande tous les 60 000 km.', 'Distribution & Moteur', 'Gates', 45.00, 20, 5),
('DST-CNT-007', 'Kit courroie accessoires Continental', 'Kit courroie accessoires avec galet. Compatible Ford Focus 1.6, Ford Mondeo 2.0, Volkswagen Golf 5 1.6. Tension stable, maintenance simple. Remplacement recommande tous les 60 000 km.', 'Distribution & Moteur', 'Continental', 110.00, 12, 5),
('DST-DYC-008', 'Joint cache-culbuteurs Dayco', 'Joint cache-culbuteurs elastomere, profil anti-fuite. Compatible Renault Clio 4 1.2, Dacia Sandero 1.2, Peugeot 206 1.4. Etancheite durable, montage facile. Remplacement recommande en cas de fuite ou a 100 000 km.', 'Distribution & Moteur', 'Dayco', 38.00, 22, 5),
('DST-INA-009', 'Poulie damper INA 6 cannelures', 'Poulie damper 6 cannelures, amortisseur caoutchouc. Compatible Peugeot 308 1.6 HDi, Citroen C5 2.0 HDi, Ford Mondeo 2.0 TDCi. Vibrations reduites, protection vilebrequin. Remplacement recommande tous les 120 000 km.', 'Distribution & Moteur', 'INA', 190.00, 8, 3),
('DST-SNR-010', 'Kit chaine distribution SNR', 'Kit chaine distribution avec patins et tendeur hydraulique. Compatible Toyota Yaris 1.3, Toyota Corolla 1.4, Kia Rio 1.4. Calage precis, bruit reduit. Remplacement recommande tous les 150 000 km.', 'Distribution & Moteur', 'SNR', 420.00, 4, 2);

-- Électricité & Éclairage (10 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('ELC-VAR-001', 'Batterie Varta 60Ah 540A', 'Batterie 12V 60Ah 540A EN, technologie calcium. Compatible Renault Clio 4, Peugeot 208, Volkswagen Polo. Demarrage fiable, faible entretien. Remplacement conseille tous les 3 a 4 ans.', 'Électricité & Éclairage', 'Varta', 180.00, 8, 3),
('ELC-BSH-002', 'Alternateur Bosch 90A', 'Alternateur 90A, poulie 6 gorges, regulateur integre. Compatible Renault Megane 3, Dacia Duster, Peugeot 308. Charge stable, rendement eleve. Controle recommande a 120 000 km.', 'Électricité & Éclairage', 'Bosch', 320.00, 5, 3),
('ELC-VAL-003', 'Demarreur Valeo 1.4kW', 'Demarreur 1.4kW, 9 dents. Compatible Ford Focus, Ford Fiesta, Citroen C3. Couple eleve, demarrage rapide. Controle recommande a 120 000 km.', 'Électricité & Éclairage', 'Valeo', 280.00, 5, 3),
('ELC-PHI-004', 'Ampoule H7 Philips Vision 55W', 'Ampoule H7 12V 55W, flux 1500 lm. Compatible Volkswagen Golf 6, Renault Clio 3, Peugeot 207. Eclairage blanc, homologation ECE. Remplacement recommande par paire tous les 20 000 km.', 'Électricité & Éclairage', 'Philips', 22.90, 60, 10),
('ELC-HEL-005', 'Ampoule H4 Hella 60/55W', 'Ampoule H4 12V 60/55W, base P43t. Compatible Dacia Logan, Toyota Yaris, Hyundai i20. Faisceau stable, duree accrue. Remplacement recommande par paire tous les 20 000 km.', 'Électricité & Éclairage', 'Hella', 18.50, 60, 10),
('ELC-NGK-006', 'Bougie allumage NGK Iridium', 'Bougie allumage iridium, ecartement 0.9mm. Compatible Toyota Corolla, Renault Megane 2, Peugeot 206. Demarrage facile, economie carburant. Remplacement recommande tous les 60 000 km.', 'Électricité & Éclairage', 'NGK', 28.00, 40, 10),
('ELC-DEN-007', 'Bobine allumage Denso crayon', 'Bobine allumage crayon, tension 25kV. Compatible Volkswagen Golf 5 1.6, Passat 1.6, Polo 1.4. Etincelle stable, ralenti regulier. Remplacement recommande tous les 80 000 km.', 'Électricité & Éclairage', 'Denso', 95.00, 15, 5),
('ELC-BSH-008', 'Capteur ABS Bosch avant', 'Capteur ABS avant, longueur cable 950mm. Compatible Peugeot 208, Citroen C4, Renault Clio 4. Signal stable, freinage securise. Remplacement recommande en cas de voyant ou a 120 000 km.', 'Électricité & Éclairage', 'Bosch', 75.00, 20, 5),
('ELC-VAL-009', 'Capteur temperature eau Valeo', 'Capteur temperature eau, filetage M12. Compatible Peugeot 301, Renault Symbol, Dacia Logan. Mesure precise, ralenti stable. Remplacement recommande a 100 000 km.', 'Électricité & Éclairage', 'Valeo', 38.00, 25, 5),
('ELC-HEL-010', 'Relais ventilateur Hella 40A', 'Relais ventilateur 40A, boitier etanche. Compatible Volkswagen Golf 6, Renault Megane 3, Peugeot 308. Protege circuit, declenchement fiable. Remplacement recommande en cas de surchauffe.', 'Électricité & Éclairage', 'Hella', 32.00, 30, 10);

-- Refroidissement (8 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('RFD-VAL-001', 'Radiateur moteur Valeo 520mm', 'Radiateur moteur 520mm, noyau alu brasage. Compatible Peugeot 301, Citroen C4, Renault Symbol. Dissipation thermique elevee, montage direct. Remplacement recommande a 120 000 km.', 'Refroidissement', 'Valeo', 320.00, 5, 3),
('RFD-NIS-002', 'Radiateur moteur Nissens 600mm', 'Radiateur moteur 600mm, double rang. Compatible Volkswagen Golf 6, Passat, Tiguan. Refroidissement stable, pression controlee. Remplacement recommande a 120 000 km.', 'Refroidissement', 'Nissens', 350.00, 4, 3),
('RFD-DYC-003', 'Pompe a eau Dayco turbine composite', 'Pompe a eau turbine composite, debit 110 L/min. Compatible Renault Clio 4, Dacia Sandero, Peugeot 208. Etancheite durable, bruit faible. Remplacement recommande avec la distribution.', 'Refroidissement', 'Dayco', 130.00, 12, 5),
('RFD-GAT-004', 'Thermostat Gates 88C', 'Thermostat 88C, corps aluminium. Compatible Toyota Corolla, Hyundai i30, Kia Ceed. Temperature stable, chauffe rapide. Remplacement recommande a 100 000 km.', 'Refroidissement', 'Gates', 55.00, 20, 5),
('RFD-GAT-005', 'Durite superieure radiateur Gates', 'Durite superieure radiateur EPDM, diametre 32mm. Compatible Renault Megane 3, Peugeot 308, Citroen C4. Resistance chaleur, montage facile. Remplacement recommande tous les 80 000 km.', 'Refroidissement', 'Gates', 35.00, 25, 10),
('RFD-NRF-006', 'Ventilateur radiateur NRF 300W', 'Ventilateur radiateur 300W, 7 pales. Compatible Ford Focus, Ford Fiesta, Volkswagen Polo. Refroidissement rapide, bruit reduit. Remplacement recommande en cas de surchauffe.', 'Refroidissement', 'NRF', 220.00, 6, 3),
('RFD-VAL-007', 'Vase expansion Valeo 1.5L', 'Vase expansion 1.5L avec capteur niveau. Compatible Peugeot 206, Citroen C3, Renault Clio 3. Plastique renforce, etancheite fiable. Remplacement recommande a 100 000 km.', 'Refroidissement', 'Valeo', 45.00, 18, 5),
('RFD-NIS-008', 'Radiateur chauffage Nissens 250mm', 'Radiateur chauffage alu 250mm. Compatible Toyota Yaris, Hyundai i20, Kia Rio. Chaleur stable, debit constant. Remplacement recommande en cas de fuite.', 'Refroidissement', 'Nissens', 160.00, 8, 3);

-- Lubrifiants & Fluides (8 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('LUB-TOT-001', 'Huile moteur Total Quartz 5W30 5L', 'Huile moteur 5W30 100% synthetique ACEA C3. Compatible Renault Megane 3 1.5 dCi, Peugeot 308 1.6 HDi, Volkswagen Golf 7 1.6 TDI. Protection turbo, economie carburant. Vidange recommande tous les 10 000 km.', 'Lubrifiants & Fluides', 'Total', 75.00, 30, 10),
('LUB-CAS-002', 'Huile moteur Castrol 5W40 5L', 'Huile moteur 5W40 synthetique, API SN. Compatible Ford Focus 1.6, Hyundai i30 1.6, Kia Ceed 1.6. Film resistant, demarrage a froid. Vidange recommande tous les 10 000 km.', 'Lubrifiants & Fluides', 'Castrol', 85.00, 25, 10),
('LUB-MOB-003', 'Huile moteur Mobil 10W40 5L', 'Huile moteur 10W40 semi-synthetique, ACEA A3/B4. Compatible Renault Logan 1.6, Peugeot 206 1.4, Chevrolet Aveo 1.4. Protection usure, bonne compression. Vidange recommande tous les 8 000 km.', 'Lubrifiants & Fluides', 'Mobil', 65.00, 28, 10),
('LUB-SHE-004', 'Huile moteur Shell Helix 5W30 5L', 'Huile moteur 5W30 synthetique, faible cendres. Compatible Volkswagen Passat 2.0 TDI, Golf 7 1.6 TDI, Polo 1.6 TDI. Protection FAP, proprete moteur. Vidange recommande tous les 15 000 km.', 'Lubrifiants & Fluides', 'Shell', 78.00, 24, 10),
('LUB-MOT-005', 'Huile moteur Motul 5W40 5L', 'Huile moteur 5W40 100% synthetique, base ester. Compatible Renault Clio 4 1.2, Toyota Yaris 1.3, Hyundai i20 1.2. Protection haute temperature, conduite dynamique. Vidange recommande tous les 10 000 km.', 'Lubrifiants & Fluides', 'Motul', 90.00, 20, 10),
('LUB-TOT-007', 'Liquide frein DOT4 Total 1L', 'Liquide frein DOT4, point ebullition 230C. Compatible Renault Clio 3, Peugeot 206, Volkswagen Polo. Pedale ferme, compatible ABS. Remplacement recommande tous les 40 000 km.', 'Lubrifiants & Fluides', 'Total', 22.00, 40, 10),
('LUB-CAS-008', 'Liquide refroidissement Castrol 5L', 'Liquide refroidissement premelange -35C, technologie OAT. Compatible Peugeot 308, Citroen C4, Ford Focus. Protection corrosion, temperature stable. Remplacement recommande tous les 60 000 km.', 'Lubrifiants & Fluides', 'Castrol', 35.00, 30, 10),
('LUB-ELF-006', 'Huile moteur Elf 10W40 5L', 'Huile moteur 10W40 semi-synthetique. Compatible Dacia Sandero 1.6, Renault Symbol 1.4, Fiat Punto 1.2. Nettoyage moteur, consommation stable. Vidange recommande tous les 8 000 km.', 'Lubrifiants & Fluides', 'Elf', 62.00, 30, 10);

-- Transmission (6 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('TRN-SCH-001', 'Kit embrayage Sachs 200mm', 'Kit embrayage complet disque 200mm, mecanisme et butee. Compatible Renault Clio 4, Dacia Sandero, Renault Logan. Pedale souple, engagement progressif. Remplacement recommande tous les 120 000 km.', 'Transmission', 'Sachs', 420.00, 5, 2),
('TRN-VAL-002', 'Kit embrayage Valeo 215mm', 'Kit embrayage complet disque 215mm. Compatible Peugeot 208, Citroen C3, Peugeot 301. Effort reduit, long cycle. Remplacement recommande tous les 120 000 km.', 'Transmission', 'Valeo', 390.00, 5, 2),
('TRN-SKF-003', 'Joint homocinetique SKF 26 cannelures', 'Joint homocinetique externe 26 cannelures. Compatible Peugeot 206, Citroen C3, Renault Clio 3. Souplesse en braquage, graisse longue duree. Remplacement recommande tous les 120 000 km.', 'Transmission', 'SKF', 140.00, 10, 5),
('TRN-SKF-004', 'Cardan complet SKF 565mm', 'Cardan complet 565mm, soufflets pre-graisses. Compatible Toyota Corolla, Hyundai i30, Kia Ceed. Equilibrage usine, vibrations reduites. Remplacement recommande a 150 000 km.', 'Transmission', 'SKF', 320.00, 5, 3),
('TRN-FAG-005', 'Roulement de boite FAG 6206', 'Roulement de boite 6206, charge dynamique elevee. Compatible Volkswagen Polo, Peugeot 208, Renault Clio 4. Rotation silencieuse, longue duree. Remplacement recommande lors de refection.', 'Transmission', 'FAG', 95.00, 12, 5),
('TRN-INA-006', 'Cable embrayage INA 1120mm', 'Cable embrayage gaine teflon, longueur 1120mm. Compatible Renault Clio 3, Dacia Logan, Peugeot 206. Effort regulier, friction reduite. Remplacement recommande tous les 120 000 km.', 'Transmission', 'INA', 45.00, 20, 5);

-- Carrosserie & Essuie-glaces (4 pièces)
INSERT INTO pieces (reference, nom, description, categorie, marque, prix_unitaire, quantite_stock, seuil_alerte) VALUES
('CRS-BSH-001', 'Balais essuie-glace Bosch Aerotwin 650/450', 'Balais essuie-glace avant 650/450mm, lame souple. Compatible Renault Clio 4, Peugeot 208, Volkswagen Polo. Essuyage silencieux, visibilite claire. Remplacement recommande tous les 12 mois.', 'Carrosserie & Essuie-glaces', 'Bosch', 55.00, 28, 10),
('CRS-VAL-002', 'Balai essuie-glace arriere Valeo 300mm', 'Balai essuie-glace arriere 300mm, fixation universelle. Compatible Dacia Duster, Renault Clio 3, Toyota Yaris. Essuyage propre, montage rapide. Remplacement recommande tous les 12 mois.', 'Carrosserie & Essuie-glaces', 'Valeo', 28.00, 35, 10),
('CRS-HEL-003', 'Retroviseur exterieur gauche Hella', 'Retroviseur gauche reglable electrique, coque a peindre. Compatible Peugeot 301, Renault Symbol, Citroen C4. Vision stable, finition robuste. Remplacement recommande en cas de casse.', 'Carrosserie & Essuie-glaces', 'Hella', 180.00, 6, 3),
('CRS-BSH-004', 'Leve-vitre avant Bosch', 'Leve-vitre avant electrique, cable acier et guidage renforce. Compatible Peugeot 207, Peugeot 208, Citroen C3. Mouvement fluide, moteur silencieux. Remplacement recommande en cas de blocage.', 'Carrosserie & Essuie-glaces', 'Bosch', 210.00, 5, 3);
