<?php

declare(strict_types=1);

return [
    'temoins' => [
        'voyant allume au tableau de bord' => 2,
        'voyant moteur allume' => 3,
        'voyant huile allume' => 3,
        'voyant batterie allume' => 2,
        'voyant abs allume' => 2,
        'voyant frein allume' => 3,
        'voyant temperature allume' => 3,
        'bruit anormal' => 2,
        'bruit metallique' => 3,
        'bruit suspension' => 2,
        'bruit transmission' => 3,
        'vibrations' => 2,
        'fumee' => 4,
        'fumee blanche' => 4,
        'fumee bleue' => 4,
        'fumee noire' => 4,
        'fuite de liquide' => 3,
        'fuite huile' => 4,
        'fuite liquide refroidissement' => 4,
        'fuite carburant' => 5,
        'perte de puissance' => 3,
        'demarrage difficile' => 2,
        'calage frequent' => 3,
        'surchauffe moteur' => 4,
        'odeur de brule' => 2,
        'direction dure' => 2,
        'freinage spongieux' => 4,
        'pedale de frein molle' => 3,
        'boite qui accroche' => 3,
        'vitesse qui saute' => 3,
        'clim ne refroidit pas' => 1,
        'consommation elevee' => 1,
        'batterie faible' => 2,
        'lampes qui clignotent' => 1,
        'vehicule immobilise' => 5,
    ],
    'temoins_aliases' => [
        'voyant' => 'voyant allume au tableau de bord',
        'voyant moteur' => 'voyant moteur allume',
        'voyant huile' => 'voyant huile allume',
        'voyant batterie' => 'voyant batterie allume',
        'voyant abs' => 'voyant abs allume',
        'voyant frein' => 'voyant frein allume',
        'voyant temperature' => 'voyant temperature allume',
        'bruit moteur' => 'bruit anormal',
        'bruit anormal moteur' => 'bruit anormal',
        'fumee visible' => 'fumee',
        'fuite d huile' => 'fuite huile',
        'fuite dhuile' => 'fuite huile',
        'fuite huile moteur' => 'fuite huile',
        'fuite liquide de refroidissement' => 'fuite liquide refroidissement',
        'fuite de liquide de refroidissement' => 'fuite liquide refroidissement',
        'fuite de carburant' => 'fuite carburant',
        'perte puissance' => 'perte de puissance',
        'ne demarre pas' => 'demarrage difficile',
        'impossible de demarrer' => 'demarrage difficile',
        'calage' => 'calage frequent',
        'surchauffe' => 'surchauffe moteur',
        'odeur brule' => 'odeur de brule',
        'volant dur' => 'direction dure',
        'frein spongieux' => 'freinage spongieux',
        'pedale molle' => 'pedale de frein molle',
        'boite accroche' => 'boite qui accroche',
        'vitesse saute' => 'vitesse qui saute',
        'clim ne fonctionne pas' => 'clim ne refroidit pas',
        'consommation haute' => 'consommation elevee',
        'lampes clignotent' => 'lampes qui clignotent',
        'immobilise' => 'vehicule immobilise',
        'vehicule immobilise' => 'vehicule immobilise',
    ],
    'types_panne' => [
        'vidange' => 1,
        'revision' => 1,
        'changement de pneu' => 1,
        'pneumatiques' => 1,
        'batterie' => 2,
        'freinage' => 3,
        'climatisation' => 1,
        'carrosserie' => 1,
        'diagnostic general' => 1,
        'autre' => 1,
        'moteur' => 3,
        'boite de vitesse' => 3,
        'electrique-batterie' => 2,
        'suspension-direction' => 2,
        'boite de vitesse' => 3,
        'electrique-batterie' => 2,
        'suspension-direction' => 2,
        'climatisation' => 1,
    ],
    'km' => [
        'seuil' => 150000,
        'score' => 1,
    ],
    'advanced' => [
        'old_rdv_hours' => 48,
        'old_rdv_score' => 1,
        'saturation_ratio' => 1.0,
        'saturation_score' => 1,
        'history_min' => 2,
        'history_score' => 1,
    ],
    'urgent_min_score' => 7,
    'max_score' => 10,
    'broadcast' => [
        'driver' => 'sse',
        'sse_log' => __DIR__ . '/../storage/urgency-events.log',
    ],
];
